Algoritmo "EstruturaComposta"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaja
// Descrição   : Estrutura de repeticao composta
// Autor(a)    : Adrielle Merces
// Data atual  : 05/09/2024
Var
   numero: inteiro

Inicio
   escreval("Digite um numero:")
   leia(numero)

   se numero < 10 entao
      escreval("Numero menor que 10")

   senao
      escreval("Numero maior que 10")

   fimse

Fimalgoritmo